language: node_js
node_js:
  - "6"
install:
  - npm install
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
  - npm test
cache:
  directories:
    - "node_modules"
